# This workflow will build a Quarkus project with GraalVM, and cache/restore any dependencies to improve the workflow execution time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Native Image Build

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17.0.7' # for a specific JDK 17; or '17' for the latest JDK 17
        distribution: 'graalvm' # New 'distribution' option
        cache: maven

    - name: Build with Maven & GraalVM
      run: ./mvnw -B package --file pom.xml -DskipTests -Pnative -Dquarkus.native.container-build=true

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
